### ISSUE TITLE
ChromTerm showing random characters on the console 

### ISSUE THREAD

**Issue by ciscohack** [hSaria/ChromaTerm#96] opened 2022-01-11 15:04 UTC
### ChromaTerm version

v0.9.0

### Terminal

iterm2 and hyperterm

### What's happening?

Hello Expert,

I have open a terminal (iterm2/hyperterm) for ssh and telnet and saw some random character appear and disappear automatically after some time. some time also see P=2s value on console and when this value appear console will not allow to do anything for small period of time.

I am using oh-my-tmux and zsh4humans as default config .

here is the link for tmux just install and use. no change and here is my zsh shell link

https://github.com/romkatv/zsh4humans/blob/v5/README.md

https://github.com/gpakosz/.tmux

![image](https://user-images.githubusercontent.com/11479557/148967021-293e02c7-e11f-4d1e-aa9e-104e9ab27663.png)

**Comment by hSaria** [comment] 2022-01-13 04:49
ChromaTerm v0.9.1 includes a fix for this issue. Thanks a lot for the bug report.

**Comment by ciscohack** [comment] 2022-01-13 05:02
Thank you. please keep thread open will test and update if any thing comes up

**Comment by ciscohack** [comment] 2022-01-13 05:32
Still seeing the characters and disappearing after few seconds.

![image](https://user-images.githubusercontent.com/11479557/149271556-b2d43e2e-f191-448d-8ed8-5d350aaba212.png)

**Comment by ciscohack** [comment] 2022-01-13 06:17
@hSaria Issue still there and seems after this upgrade and facing some performance issue like sometime when i trying to select text it won't work intermittently

![image](https://user-images.githubusercontent.com/11479557/149276092-f821043d-7fec-4f28-8e2d-8d2c4fce9068.png)

**Comment by hSaria** [comment] 2022-01-13 13:30
Can you please not crop the screenshot too much? There’s vital information before and after those codes that speed up my work.

**Comment by ciscohack** [comment] 2022-01-13 13:45
> Can you please not crop the screenshot too much? There’s vital information before and after those codes that speed up my work.
> […](#)
> On 13 Jan 2022, at 6:18 am, ciscohack ***@***.***> wrote: ﻿ @hSaria Issue still there and seems after this upgrade and facing some performance issue like sometime when i trying to select text it won't work intermittently — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.

@hSaria not cropped up infact captured only random characters after this character logs and ssh details which no point to share

**Comment by hSaria** [comment] 2022-01-13 14:04
I'm having trouble recreating this issue. Could you disable terminal-wide `ct` then, in a new tab, run  `ct zsh --login | tee -a output.txt` and keep working until you run into the issue. Once you do, immediately close the session and attach `output.txt`.

Note that the output is being stored to `output.txt`. I'm only interested in the last few lines that include the trigger for this bug, so if the file is too large, you can `head -500 output.txt > smaller-output.txt`.

**Comment by ciscohack** [comment] 2022-01-13 14:59
> I'm having trouble recreating this issue. Could you disable terminal-wide `ct` then, in a new tab, run `ct zsh --login | tee -a output.txt` and keep working until you run into the issue. Once you do, immediately close the session and attach `output.txt`.
> 
> Note that the output is being stored to `output.txt`. I'm only interested in the last few lines that include the trigger for this bug, so if the file is too large, you can `head -500 output.txt > smaller-output.txt`.

@hSaria sure will try

**Comment by ciscohack** [comment] 2022-01-13 15:16
I disabled terminal-wide ct and using ct zsh --login so far result is much better not seens issue so far on hyperterm ... will see if i find the issue will upload the file

**Comment by hSaria** [comment] 2022-01-13 15:54
It shouldn’t make a different if you use terminal-wide highlighting; I use it and can’t recreate the issues you’re having. You’re only using the command I provided to log your output.

**Comment by ciscohack** [comment] 2022-01-13 17:05
> It shouldn’t make a different if you use terminal-wide highlighting; I use it and can’t recreate the issues you’re having. You’re only using the command I provided to log your output.
> […](#)
> On 13 Jan 2022, at 3:16 pm, ciscohack ***@***.***> wrote: ﻿ I disabled terminal-wide ct and using ct zsh --login so far result is much better not seens issue so far on hyperterm ... will see if i find the issue will upload the file — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.

I did two thing today i cleared the cache then i changed my system wide terminal highlight from /bin/zsh --login to zsh --login and i would like to say so far results are smooth and expected not random character and no issue so far testing since last 1 hour...

**Comment by hSaria** [comment] 2022-01-13 17:21
Not sure what cache you’re referring to, but regards to /bin/zsh vs zsh, they’re both the same binary, except the former uses the absolute path while the latter uses $PATH lookup.

At any rate, I’ll keep this open for a couple of days in case you run into anything.

**Comment by ciscohack** [comment] 2022-01-13 17:33
> Not sure what cache you’re referring to, but regards to /bin/zsh vs zsh, they’re both the same binary, except the former uses the absolute path while the latter uses $PATH lookup. At any rate, I’ll keep this open for a couple of days in case you run into anything.
> […](#)
> On 13 Jan 2022, at 5:05 pm, ciscohack ***@***.***> wrote: ﻿ It shouldn’t make a different if you use terminal-wide highlighting; I use it and can’t recreate the issues you’re having. You’re only using the command I provided to log your output. … On 13 Jan 2022, at 3:16 pm, ciscohack @.***> wrote: ﻿ I disabled terminal-wide ct and using ct zsh --login so far result is much better not seens issue so far on hyperterm ... will see if i find the issue will upload the file — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned. I did two thing today i cleared the cache then i changed my system wide terminal highlight from /bin/zsh --login to zsh --login and i would like to say so far results are smooth and expected not random character and no issue so far testing since last 1 hour... — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.

Yes you are correct the path is same but saw some improvement but finally i hit the issue once. but i forgot to turn on the log you asked me to get.

**Comment by hSaria** [comment] 2022-01-13 17:46
Do you remember the circumstances before you ran into that issue? For instance,
- were in the middle of typing a command?
- which programs were you running inside of the shell (e.g. ssh, tmux, etc…)
- what was the output before and after the issue appeared?

**Comment by ciscohack** [comment] 2022-01-13 17:53
> Do you remember the circumstances before you ran into that issue? For instance, - were in the middle of typing a command? - which programs were you running inside of the shell (e.g. ssh, tmux, etc…) - what was the output before and after the issue appeared?
> […](#)
> On 13 Jan 2022, at 5:34 pm, ciscohack ***@***.***> wrote: ﻿ Not sure what cache you’re referring to, but regards to /bin/zsh vs zsh, they’re both the same binary, except the former uses the absolute path while the latter uses $PATH lookup. At any rate, I’ll keep this open for a couple of days in case you run into anything. … On 13 Jan 2022, at 5:05 pm, ciscohack @.> wrote: ﻿ It shouldn’t make a different if you use terminal-wide highlighting; I use it and can’t recreate the issues you’re having. You’re only using the command I provided to log your output. … On 13 Jan 2022, at 3:16 pm, ciscohack @.> wrote: ﻿ I disabled terminal-wide ct and using ct zsh --login so far result is much better not seens issue so far on hyperterm ... will see if i find the issue will upload the file — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned. I did two thing today i cleared the cache then i changed my system wide terminal highlight from /bin/zsh --login to zsh --login and i would like to say so far results are smooth and expected not random character and no issue so far testing since last 1 hour... — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned. Yes you are correct the path is same but saw some improvement but finally i hit the issue once. but i forgot to turn on the log you asked me to get. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.

@hSaria  I was reading one 8000 plus line log file on hyperterm inside zsh/tmux(detail already shared) and while scrolling down to logs random character pop up and the moment i scroll again it's disappear and everything works fine.

I always use bat tool to read logs offline and this time also i used bat to read that log

**Comment by hSaria** [comment] 2022-01-13 18:43
I was able to recreate the problem. Do you mind testing out the fix by running the following
```shell
patch /usr/local/lib/python3.9/site-packages/chromaterm/__main__.py << EOF
327c327
<             elif len(data) < 2 + data.count(b'\b') * 2:
---
>             elif len(data) < 2 + data.count(b'\b') * 2 and data[:1] != b'\x1b':
EOF
```

Make sure to restart your terminal sessions for the change to take effect.

**Comment by ciscohack** [comment] 2022-01-13 18:46
@hSaria finally issue happened once again. Here is the screenshot of the issue and output log.

[Output.txt](https://github.com/hSaria/ChromaTerm/files/7865229/Output.txt)


![image](https://user-images.githubusercontent.com/11479557/149389642-3b26180e-31dd-461f-b643-46db80bf3af0.png)

**Comment by ciscohack** [comment] 2022-01-13 18:47
> I was able to recreate the problem. Do you mind testing out the fix by running the following
> 
> ```shell
> patch /usr/local/lib/python3.9/site-packages/chromaterm/__main__.py << EOF
> 327c327
> <             elif len(data) < 2 + data.count(b'\b') * 2:
> ---
> >             elif len(data) < 2 + data.count(b'\b') * 2 and data[:1] != b'\x1b':
> EOF
> ```
> 
> Make sure to restart your terminal sessions for the change to take effect.

I have ran this command as you mentioned. Thanks

**Comment by hSaria** [comment] 2022-01-13 19:01
> @hSaria finally issue happened once again. Here is the screenshot of the issue and output log.
> 
> [Output.txt](https://github.com/hSaria/ChromaTerm/files/7865229/Output.txt)
> 
> ![image](https://user-images.githubusercontent.com/11479557/149389642-3b26180e-31dd-461f-b643-46db80bf3af0.png)

Thanks a lot for the file. That's the same effect I was able to reproduce

**Comment by ciscohack** [comment] 2022-01-13 19:06
> > @hSaria finally issue happened once again. Here is the screenshot of the issue and output log.
> > [Output.txt](https://github.com/hSaria/ChromaTerm/files/7865229/Output.txt)
> > ![image](https://user-images.githubusercontent.com/11479557/149389642-3b26180e-31dd-461f-b643-46db80bf3af0.png)
> 
> Thanks a lot for the file. That's the same effect I was able to reproduce

Glad, i could able to help you in repro

**Comment by hSaria** [comment] 2022-01-14 05:21
v0.9.2 released. It includes the fix.

**Closed** 2022-01-14 05:22 UTC
Labels: bug

**Comment by ciscohack** [comment] 2022-01-14 06:05
To reproduce the issue used my last shared config and install moar (https://github.com/walles/moar) open any big file and search and hide number through arrow key .. you will see latency if terminal wide highlighter enabled

**Comment by hSaria** [comment] 2022-01-14 13:31
> @hSaria Please keep it open. 

Issues are not meant to be open. Once an issue is fixed, then it can be closed. Otherwise, I will end up with an issue like #95 which is extremely long and has lost all meaning.

The problem you're describing is different than what was described in this issue #96.

I'm going to open an issue referencing what you mentioned, but for the future, make sure you open a new issue when the problem is not related to the original one reported.
